main: de.spurkomet.must.InternalMainClass
name: must
version: 1.18.2
description: Must, Rust in Minecraft
api-version: 1.18
author: [SpurKomet, DrHadrian]
libraries:
  - "net.axay:kspigot:1.18.2"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.6.20"